DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS logs CASCADE;

CREATE TABLE recipes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  directions TEXT[]
);

CREATE TABLE logs (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  recipe_id BIGINT REFERENCES recipes(id),
  date_of_event TEXT NOT NULL,
  notes TEXT NOT NULL,
  rating BIGINT NOT NULL
);
